export const ITINERARY_STATUSES = [
  { value: 'draft', label: 'Draft' },
  { value: 'sent', label: 'Sent' },
  { value: 'approved', label: 'Approved' },
  { value: 'rejected', label: 'Rejected' },
  { value: 'published', label: 'Published' },
]

export const DEFAULT_ITINERARY_FORM = {
  tripName: '',
  customerName: '',
  customerEmail: '',
  phone: '',
  destination: '',
  country: '',
  bannerImage: '',
  startDate: '',
  endDate: '',
  numberOfAdults: 2,
  numberOfChildren: 0,
  pricePerPerson: 0,
  totalPrice: 0,
  currency: 'USD',
  status: 'draft',
  notes: '',
  assignedTo: '',
  hotels: [],
  flights: [],
  transfers: [],
  visa: { required: false, type: '', processingDays: '', cost: 0, notes: '' },
  inclusions: [''],
  exclusions: [''],
  termsAndConditions: '',
  gallery: [],
  days: [],
}

export const DEFAULT_DAY = {
  dayNumber: 1,
  sortOrder: 0,
  title: '',
  description: '',
  hotel: { name: '', location: '', checkIn: '', checkOut: '', stars: 0, notes: '' },
  meals: [],
  activities: [],
  transfers: [],
  timelineBlocks: [],
  notes: '',
  images: [],
}
